### ISSUE TITLE
the plugin does not work

### ISSUE THREAD

**Issue by lootoos** [james090500/VelocityWhitelist#1]
I use Java 18
I use velocity:https://papermc.io/downloads#Velocity #169

**Comment by james090500** [comment]
Plugin works fine for me, any logs or useful information?

**Comment by lootoos** [comment]
I use online mode = false

**Comment by james090500** [comment]
Offline isn't supported. Probably because people dont have uuids

**Comment by lootoos** [comment]
is that why the plugin didn't work for me?
can you add support for offline mode?
